// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASrYU-HedWD5tHzxfvDFe28aXy0DHzhmw',
    appId: '1:922242290040:web:f3d09ccb2fa52dd61bf88d',
    messagingSenderId: '922242290040',
    projectId: 'edemy-2b816',
    authDomain: 'edemy-2b816.firebaseapp.com',
    storageBucket: 'edemy-2b816.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmsdGcaIHZV_yoio-s4i3GIg83lpHkHyc',
    appId: '1:922242290040:android:89948cb581c738921bf88d',
    messagingSenderId: '922242290040',
    projectId: 'edemy-2b816',
    storageBucket: 'edemy-2b816.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGBBh7YVRGUqRIWT2ZoUwLgEq42ePGwiM',
    appId: '1:922242290040:ios:b7f3a9796346d74a1bf88d',
    messagingSenderId: '922242290040',
    projectId: 'edemy-2b816',
    storageBucket: 'edemy-2b816.appspot.com',
    iosBundleId: 'com.example.carbonFootprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGBBh7YVRGUqRIWT2ZoUwLgEq42ePGwiM',
    appId: '1:922242290040:ios:3ec01561764c058c1bf88d',
    messagingSenderId: '922242290040',
    projectId: 'edemy-2b816',
    storageBucket: 'edemy-2b816.appspot.com',
    iosBundleId: 'com.example.carbonFootprint.RunnerTests',
  );
}
